### ISSUE TITLE
Documentation needed - Twitch Upcoming Ad

### ISSUE THREAD

**Issue by rondhi** [Streamerbot/docs#112]
**Describe the missing documentation**
Twitch Upcoming Ad Trigger being added to v0.2.3

**Where do you think this documentation should be included? An existing page or new page?**
New page needed https://docs.streamer.bot/api/triggers/twitch/ads/upcoming-ad

**Additional context**
"`%minutes%`"	"5"
"`%nextAdAt%`"	"2024-03-03 01:10:20"
"`%snoozesLeft%`"	"3"
"`%adLength%`"	"150"

Attached is a list of variables

**Comment by Whipstickgostop** [comment]
ty, added
