### ISSUE TITLE
Compatible with Streamlabs' Dual Output Mode

### ISSUE THREAD

**Issue by benzhe** [Streamerbot/docs#139]
**Describe the bug**
When the Dual Output feature is enabled in Streamlabs, Streamer.bot's Streamlabs Action can only control the visibility of the Vertical output source, Horizontal output does not take effect.

**To Reproduce**
1. Enable Dual Output Mode in Streamlabs OBS;
2. Add Streamlabs connection in Streamer.bot;
3. Add Streamlabs Source Visibility Action in Streamer.bot;
4. Test the Action, only the source in Vertical output in Streamlabs works, not Horizontal output;
5. Disable Streamlabs' Dual Ouput Mode, leaving the Horizontal output;
6. Test the Action again, nothing happen.

**Expected behavior**
Streamlabs Source Visibility Control Action should work in both Horizontal and Vertical output;

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by nate1280** [comment]
This is an issue site for Streamer.bot documentation, not for application feature requests/etc.
