### ISSUE TITLE
Documentation Needed - GetEventType

### ISSUE THREAD

**Issue by dark-swordsman** [Streamerbot/docs#225]
## **Describe the missing documentation**

[GetEventType](https://docs.streamer.bot/api/csharp/core/events#GetEventType) is not really clear on how to use it or `EventType` appropriately.

The dropdown is nice since it shows all the types. However, it doesn't clarify that when you access `EventType` to compare the result of `GetEventType()`, it's actually `<Prefix><Event>`.

So for example, it would be assumed based on this UI that I would probably do `EventType.AdMidRoll`, or perhaps even `EventType.Twitch.AdMidroll`. However, it's actually `EventType.TwitchAdMidRoll`. 

![image](https://github.com/user-attachments/assets/b02aa838-bf06-426b-8b64-e11af46c857c)

## **Where do you think this documentation should be included? An existing page or new page?**

I think [the existing documentation for GetEventType](https://docs.streamer.bot/api/csharp/core/events#GetEventType) should be updated with both a better "CPH Example", as well as a note/disclaimer about the `<Prefix><Event>` format.

For the CPH Example, I think something [similar to the example on this separate repo](https://github.com/pwnyy/Streamer.bot-Useful-Data/blob/main/EventType_EventSource_Data.md) would be a good example to use.

As for the note/disclaimer (presumably using `::note` or `::tip`), it would probably be something like:

> The returned value of `EventType` is in the format of `<Prefix><Event>`. As an example, the `Twitch` event `AdRun` would be `TwitchAdRun`. You could compare it as `GetEventType() == EventType.TwitchAdRun`.

**Comment by Whipstickgostop** [comment]
Updated 👍
