### ISSUE TITLE
Documentation needed for Settings > Credits

### ISSUE THREAD

**Issue by rondhi** [Streamerbot/docs#229]
**Describe the missing documentation**
A docs page for Settings > Credits

**Where do you think this documentation should be included? An existing page or new page?**
Under Settings. New Page

**Additional context**

Credits that are recorded:

### Events to Record
- Follows
- Cheers
- Subs
- ReSubs
- Gift Subs
- Gift Bombs
- Raided
- Reward Redemptions
- Goal Contributions
- Game Updates
- Pyramids
- Hype Trains

### Users Present (spoke)
- Editors
- Moderators
- Subscribers
- VIPs
- Groups
  - Groups can be created via the `Settings > Groups` tab
- Users

### Track Top
- Cheer
- Channel Points Used

## Auto-Reset
This reset is triggered when Streamer.bot has been closed for this many hours. Default value is `12` hours.
Can be reset manually via the `Reset` button, the subaction `Sub-actions > Settings > Reset Credits`, or the C# method `CPH.ResetCredits()`

**Comment by rondhi** [comment]
![image](https://github.com/user-attachments/assets/bfcc25fd-58fc-4680-9382-7f9060b500d7)

**Comment by Mustached-Maniac** [comment]
Added Credits.md
