### ISSUE TITLE
Documentation needed: Auto-Updater

### ISSUE THREAD

**Issue by lebluxtv** [Streamerbot/docs#31]
**Describe the missing documentation**
Accessing and using the update option from hamburger button

**Where do you think this documentation should be included? An existing page or new page?**
new page: /guide/update
[Update Page from Old wiki](https://wiki.streamer.bot/en/Update)

**Additional context**
![image](https://github.com/Streamerbot/docs/assets/136271820/6fca7b1e-aaf5-45dd-ae8e-160b764c04b0)
![image](https://github.com/Streamerbot/docs/assets/136271820/1a8d7adf-c545-4e8a-b041-288cde75a063)

**Comment by Whipstickgostop** [comment]
This can probably just be briefly described on the installation page or somewhere else. 
I don't think it really needs it's own page.

The primary thing we need documented is just how to get alpha/beta updates.

**Comment by Whipstickgostop** [comment]
Added info to the installation page
