### ISSUE TITLE
Documentation needed: OBS Events

### ISSUE THREAD

**Issue by lebluxtv** [Streamerbot/docs#32]
**Describe the missing documentation**
link to full references of all OBS WebSocket 5 events

**Where do you think this documentation should be included? An existing page or new page?**
existing : /api/triggers/obs/event

**Additional context**
[obs-websocket-doc](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md)

**Comment by Whipstickgostop** [comment]
Added
