### ISSUE TITLE
Documentation needed: File update for the HTML overlay ( v1.0.1 )

### ISSUE THREAD

**Issue by lebluxtv** [Streamerbot/docs#36]
**Describe the missing documentation**
File update for the HTML overlay ( v1.0.1 )

**Where do you think this documentation should be included? An existing page or new page?**
file exist : /guide/extra-features/html-overlay#download

**Additional context**
[Github link to the new file](https://github.com/Streamerbot/html-windows-overlay/releases/tag/1.0.1)
this is stored in a location I can't directly access

**Comment by Whipstickgostop** [comment]
I need to update this on the CDN

**Comment by Whipstickgostop** [comment]
Can also include additional documentation from Ruu's README: https://github.com/Streamerbot/html-windows-overlay/blob/1.0.1/readme.md

**Comment by lebluxtv** [comment]
I have no access to that page :
https://github.com/Streamerbot/html-windows-overlay/blob/1.0.1/readme.md

**Comment by Whipstickgostop** [comment]
Updated
