### ISSUE TITLE
Documentation needed  Cheers event : missing Badges Variables

### ISSUE THREAD

**Issue by lebluxtv** [Streamerbot/docs#79]
**Describe the missing documentation**
Badges are not shown as available data from Cheers event

**Where do you think this documentation should be included? An existing page or new page?**
https://docs.streamer.bot/api/triggers/twitch/chat/cheer

**Additional context**

![image](https://github.com/Streamerbot/docs/assets/136271820/313dc99a-95ba-4666-bc7f-790002eb99dd)

**Comment by Ik1497** [comment]
This is documented under Twitch User
