### ISSUE TITLE
Documentation needed - ObsSetFilterState C# Method

### ISSUE THREAD

**Issue by rondhi** [Streamerbot/docs#96]
**Describe the missing documentation**
It's not exactly clear (just from looking at documentation) what each value in `int state` does.
- 0 = enable
- 1 = disable
- 2 = toggle

**Where do you think this documentation should be included? An existing page or new page?**
https://docs.streamer.bot/api/csharp/method/ObsSetFilterState

**Comment by Ik1497** [comment]
Will add when issue #85 is completed

**Comment by Whipstickgostop** [comment]
added
